name: Test on windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-window:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
